---
- name: Install Bacula Client
  yum:
    name: bacula-client-{{ bacula_client_version }}

- name: Configure Bacula Client
  template:
    dest: /etc/bacula/bacula-fd.conf
    src: bacula-fd.conf.j2
    mode: 0640
    owner: root
    group: root
  notify: restart bacula-client
